

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TRPO_220_Testirovanie
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class TestirovanieEntities : DbContext
{
    public TestirovanieEntities()
        : base("name=TestirovanieEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Group> Group { get; set; }

    public virtual DbSet<QuestType> QuestType { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<StudenInformation> StudenInformation { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<TestQInformation> TestQInformation { get; set; }

    public virtual DbSet<TestReport> TestReport { get; set; }

    public virtual DbSet<Users> Users { get; set; }

}

}

