
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TRPO_220_Testirovanie
{

using System;
    using System.Collections.Generic;
    
public partial class StudenInformation
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public StudenInformation()
    {

        this.TestReport = new HashSet<TestReport>();

    }


    public int StudentID { get; set; }

    public int GroupID { get; set; }

    public string FirstName { get; set; }

    public string SecondName { get; set; }

    public string Patronymic { get; set; }



    public virtual Group Group { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TestReport> TestReport { get; set; }

}

}
